version: '3.7'

services:
  runner1:
    hostname: runner1
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - type: bind
        source: ${GITLAB_RUNNERS_HOME}/runner1/config
        target: /etc/gitlab-runner
        bind:
          create_host_path: true
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/opt/scripts:ro
    networks:
        - gitlab-network
    entrypoint: 
      - /usr/bin/dumb-init
      - --
    command: 
      - bash
      - -c
      - /opt/scripts/register.sh && /opt/scripts/run.sh
    env_file:
     - .env

  runner2:
    hostname: runner2
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - type: bind
        source: ${GITLAB_RUNNERS_HOME}/runner2/config
        target: /etc/gitlab-runner
        bind:
          create_host_path: true
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/opt/scripts:ro
    networks:
        - gitlab-network
    entrypoint: 
      - /usr/bin/dumb-init
      - --
    command: 
      - bash
      - -c
      - /opt/scripts/register.sh && /opt/scripts/run.sh
    env_file:
     - .env

networks:
  gitlab-network:
    name: gitlab-network